[package]
name = "xforcesolutions"
version = "0.1.0"

[leptos]
# The site root folder is where cargo-leptos generates all output
site-root = "target/site"

# The site package directory is where the app's static assets are located
site-pkg-dir = "pkg"

# The browserlist query used for optimizing the CSS
browserquery = "defaults"

# The environment Leptos will run in (static site)
env = "PROD"

# The features to use when compiling the lib target (client-side only)
lib-features = ["hydrate"]

# The profile to use for the lib target when compiling for release
lib-profile-release = "wasm-release"

# Assets source directory
assets-dir = "frontend"

# The output name used by cargo-leptos for the client-side bundle
output-name = "xforcesolutions"

# The tailwind input file
tailwind-input-file = "frontend/style/tailwind.css"

# The tailwind config file
tailwind-config-file = "frontend/tailwind.config.js"

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
